language: java

sudo: false # faster builds

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean compile
  - if [ "$TRAVIS_BRANCH" = "master" ]; then mvn clean test; mvn package -Dmaven.test.skip=true; mvn -s .travis/settings.xml sonar:sonar; fi
  - if [ "$TRAVIS_BRANCH" = "release" ]; then chmod +x .travis/prepare.sh && ./travis/prepare.sh; mvn -s .travis/settings.xml -B release:clean release:prepare; git push --tags; mvn -s .travis/settings.xml -B release:perform; mvn generate-sources; chmod +x ./push.sh && ./push.sh; fi

after_success:
- bash <(curl -s https://codecov.io/bash)