server:
  port: 8081
  
keycloak:
    url: ${KEYCLOAK_URL:http://localhost:8080/auth}
    realm: ${KEYCLOAK_REALM:test}
    client_id: ${KEYCLOAK_CLIENT_ID:test}
    
logging:
    level:
      root: info*
    pattern:
      console: "%d [%thread] %-5level %logger %M : %msg%n*"
    file: ${LOGGING_FILE:./positive.log}
    
spring:
    jackson:
      serialization:
        INDENT_OUTPUT: true