server:
  port: 8081
  
keycloak:
    url: ${KEYCLOAK_URL:http://localhost:8080/auth}
    realm: ${KEYCLOAK_REALM:test}
    client_id: ${KEYCLOAK_CLIENT_ID:test}
    client_secret: ${KEYCLOAK_SECRET:copyfromkeycloakinterfaz}
    
spring:
    profiles:
      active: ${LOGGING_MODE:dev}
    jackson:
      serialization:
        INDENT_OUTPUT: true